# Generated by Django 4.2.4 on 2023-10-05 03:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'id__ne': models.F('id')}, related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
