# Generated by Django 4.2.4 on 2023-10-06 01:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('pk', models.F('pk')), _negated=True), related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
    ]
