# Generated by Django 4.2.4 on 2023-08-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.IntegerField(verbose_name='Starting bid($)'),
        ),
    ]
