# Generated by Django 4.2.4 on 2023-08-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='starting_bid',
            field=models.FloatField(verbose_name='Starting bid($)'),
        ),
    ]
