# Generated by Django 4.2.4 on 2023-08-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2023-08-28', verbose_name='Create at'),
            preserve_default=False,
        ),
    ]
