# Generated by Django 4.2.4 on 2023-08-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='image',
        ),
    ]
