# Generated by Django 4.2.4 on 2023-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, upload_to='images/'),
        ),
    ]
