# Generated by Django 4.2.4 on 2023-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auctionlisting_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.FloatField(default=10, verbose_name='Current bid($)'),
        ),
    ]
