# Generated by Django 4.2.4 on 2023-08-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_testing_delete_bid_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
