# Generated by Django 4.2.4 on 2023-08-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.FloatField(blank=True, null=True, verbose_name='Current bid($)'),
        ),
    ]
